variant: flatcar
version: 1.0.0
# These configurations start Docker as a service; install Docker compose with automatic updates
systemd:
  units:
    - name: docker.service
      enabled: true
    - name: systemd-sysupdate.timer
      enabled: true
    - name: systemd-sysupdate.service
      dropins:
        - name: docker_compose.conf
          contents: |
            [Service]
            ExecStartPre=/usr/bin/sh -c "readlink --canonicalize /etc/extensions/docker_compose.raw > /tmp/docker_compose"
            ExecStartPre=/usr/lib/systemd/systemd-sysupdate -C docker_compose update
            ExecStartPost=/usr/bin/sh -c "readlink --canonicalize /etc/extensions/docker_compose.raw > /tmp/docker_compose-new"
            ExecStartPost=/usr/bin/sh -c "if ! cmp --silent /tmp/docker_compose /tmp/docker_compose-new; then touch /run/reboot-required; fi"
storage:
  links:
    - path: /etc/systemd/system/multi-user.target.wants/docker.service
      target: /usr/lib/systemd/system/docker.service
      hard: false
      overwrite: true
    - target: /opt/extensions/docker_compose/docker_compose-2.24.5-x86-64.raw
      path: /etc/extensions/docker_compose.raw
      hard: false
      overwrite: true
  files:
    - path: /opt/extensions/docker_compose/docker_compose-2.24.5-x86-64.raw
      mode: 0644
      overwrite: true
      contents:
        source: https://github.com/flatcar/sysext-bakery/releases/download/latest/docker_compose-2.24.5-x86-64.raw
    - path: /etc/sysupdate.docker_compose.d/docker_compose.conf
      overwrite: true
      contents:
        source: https://github.com/flatcar/sysext-bakery/releases/download/latest/docker_compose.conf
    - path: /etc/sysupdate.d/noop.conf
      overwrite: true
      contents:
        source: https://github.com/flatcar/sysext-bakery/releases/download/latest/noop.conf